language: R
cache: packages
warnings_are_errors: true
r_check_args: --as-cran --run-donttest

r_packages:
  # Online documentation
  - pkgdown

branches:
  only:
    - master

before_deploy:
  - cp releases/CHANGELOG.md .
  - Rscript -e 'install.packages(getwd(), repos = NULL, type = "source"); pkgdown::build_site()'
  - cp pkgdown/favicon/* docs/
deploy:
  provider: pages
  local_dir: docs/
  skip_cleanup: true
  github-token: $GH_TOKEN
