# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tree_search_rcpp <- function(X, Y, depth, split_step, min_node_size, reward_type, lambda) {
    .Call('_policytree_tree_search_rcpp', PACKAGE = 'policytree', X, Y, depth, split_step, min_node_size, reward_type, lambda)
}

tree_search_rcpp_predict <- function(tree_array, X) {
    .Call('_policytree_tree_search_rcpp_predict', PACKAGE = 'policytree', tree_array, X)
}

