# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tree_search_rcpp <- function(X, Y, depth) {
    .Call('_policytree_tree_search_rcpp', PACKAGE = 'policytree', X, Y, depth)
}

